# Site settings
title: Mohsen Azimi
email: mohsen@mohsenweb.com
description: Mohsen Azimi's personal weblog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mohsenweb.com" # the base hostname & protocol for your site
twitter_username: "mohsen____"
github_username:  mohsen1

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
